### PR TITLE
clean kb loop by resetting result variable

### PR DESCRIPTION
**Pull request by MaikKram**
if get-kbupdate input is not only a single kb, you may receive the output from the first kb over and over again. to fix that the result variable in the foreach kb loop needs to be reset on every iteration, because it can be that you drag the result from the previous iteration within. The conditions inside the loop don't process it well.

### CODE REVIEW

**Comment by RMMSecurity** [comment]
I was just going to report this problem I ran into after trying to use kbupdate to pull down a list of the SSUs and LCUs.  Thanks!!

@potatoqualitee any chance this will be able to be fast tracked with a db update?  😊

**Comment by potatoqualitee** [comment]
yep! merging and gonna update shortly. thanks everyone for your support! I'm knee deep in another project and not working on this one currently.

**Comment by potatoqualitee** [comment]
change is now in 1.1.7. I upped it a few versions cuz I messed up on some signatures 💯

**Comment by RMMSecurity** [comment]
You're the best!

**Pull request merged**
