### PR TITLE
Support for force scanning against Windows Update

### PR DESCRIPTION
**Pull request by codaamok**
Hey, I hope you're well! Don't merge just yet, I have a question 😄 

I have done two things in this PR:

- Added support to specify `-UseWindowsUpdate` in `Get-KbNeededUpdate`; this lets users "forcefully" search against Windows Update even if Windows is configured to scan against WSUS - achieved by just setting ServerSelection to 2 on the UpdateServer interface.
- Removed `-Credential` parameter from `Connect-KbWsusServer` as it wasn't used

Do I need to do anything special to build the module in order to test with it? I still need to some more testing but initial testing proves OK. Right now I'm just modifying locally and importing the module from the repository.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thanks so much @codaamok! no, you do not need anything special other than sometimes using -Force when using Import-Module to ensure your changes are enabled. This change looks solid and the integration tests pass 😊

**Comment by codaamok** [comment]
I made some more changes:

- Forgot to add `DefaultParameterSetName` attribute; it threw an error not knowing which param set to use when the function was called without any params
- I made somewhat of an overhaul in the comment based help and readme to
  - consistently named the Windows Update cloud service as "Windows Update (cloud service)", instead of "Microsoft update catalog"
  - consistently named the Windows Update offline scan file (`wsusscn2.cab`) as such
  - consistently name the Windows Update Agent so it wasn't confused with Windows Update (the cloud service)

Let me know your thoughts

**Comment by codaamok** [comment]
Oh I think I'll add `-UseWindowsUpdate` in `Install-KbUpdate`, too

**Comment by potatoqualitee** [comment]
Thanks again, this code looks great -- appreciate the added functionality 👍🏼 Will merge and publish once tests pass again.

**Pull request merged**
